import fs from "node:fs";
import path from "node:path";

import { assert, readJson, toAbs } from "./tools/validators/fs-utils.ts";
import { errorMessage, isRecord } from "./tools/types.ts";

const paths = {
  source: "docs/protocol/error-rules.json",
  rustMod: "crates/docnav-protocol/src/generated/mod.rs",
  rustRules: "crates/docnav-protocol/src/generated/error_rules.rs",
  jsRules: "scripts/tools/validators/generated/error-rules.ts",
  protocolResponseSchema: "docs/schemas/protocol-response.schema.json"
};

const generatedErrorDetailsDefPrefix = "generatedProtocolErrorDetails";
const generatedErrorDetailsDefPrefixes = [
  generatedErrorDetailsDefPrefix,
  "generatedErrorDetails"
];

type ErrorRule = {
  code: string;
  rust_variant: string;
  required_details: string[];
};

type ErrorRules = {
  version: string;
  errors: ErrorRule[];
};

type Options = {
  checkOnly: boolean;
};

type JsonSchemaValue = boolean | null | number | string | JsonSchemaObject | JsonSchemaValue[];
type JsonSchemaObject = { [key: string]: JsonSchemaValue };

const generatedHeader = (sourcePath: string): string =>
  `// This file is generated by scripts/generate-error-rules.ts from ${sourcePath}.\n` +
  "// Do not edit by hand.\n\n";

function parseArgs(args: string[]): Options {
  const options: Options = {
    checkOnly: false
  };

  for (const arg of args) {
    if (arg === "--check" && !options.checkOnly) {
      options.checkOnly = true;
      continue;
    }
    throw new Error(`unknown argument: ${arg}`);
  }

  return options;
}

function isJsonSchemaObject(value: unknown): value is JsonSchemaObject {
  return isRecord(value);
}

function validateRules(rules: unknown): asserts rules is ErrorRules {
  assert(isRecord(rules), "error rules root must be an object");
  assert(typeof rules.version === "string", "error rules version must be a string");
  assert(Array.isArray(rules.errors), "error rules errors must be an array");
  assert(rules.errors.length > 0, "error rules errors must not be empty");

  const codes = new Set<string>();
  const variants = new Set<string>();
  for (const [index, error] of rules.errors.entries()) {
    const label = `errors[${index}]`;
    assert(isRecord(error), `${label} must be an object`);
    const requiredDetails = error.required_details;
    assert(
      Array.isArray(requiredDetails) && requiredDetails.length > 0,
      `${label}.required_details must be a non-empty array`
    );
    assert(
      requiredDetails.every((field): field is string => typeof field === "string"),
      `${label}.required_details must contain only strings`
    );

    const code = error.code;
    const rustVariant = error.rust_variant;
    assert(typeof code === "string", `${label}.code must be a string`);
    assert(typeof rustVariant === "string", `${label}.rust_variant must be a string`);
    assert(/^[A-Z][A-Z0-9_]*$/.test(code), `${label}.code is invalid`);
    assert(/^[A-Z][A-Za-z0-9]*$/.test(rustVariant), `${label}.rust_variant is invalid`);
    assert(!codes.has(code), `${label}.code duplicates ${code}`);
    assert(!variants.has(rustVariant), `${label}.rust_variant duplicates ${rustVariant}`);
    codes.add(code);
    variants.add(rustVariant);

    const detailFields = new Set<string>();
    for (const field of requiredDetails) {
      assert(/^[a-z][a-z0-9_]*$/.test(field), `${label}.required_details contains invalid field ${field}`);
      assert(!detailFields.has(field), `${label}.required_details duplicates ${field}`);
      detailFields.add(field);
    }
  }
}

function generateRustMod() {
  return `${generatedHeader(paths.source)}pub(crate) mod error_rules;\n`;
}

function generateRustRules(rules: ErrorRules): string {
  const arms = rules.errors
    .map((error) => {
      const details = error.required_details.map((field) => `"${field}"`).join(", ");
      return `        StableErrorCode::${error.rust_variant} => &[${details}],`;
    })
    .join("\n");

  return (
    generatedHeader(paths.source) +
    "use crate::StableErrorCode;\n\n" +
    "pub(crate) const fn required_details(code: StableErrorCode) -> &'static [&'static str] {\n" +
    "    match code {\n" +
    `${arms}\n` +
    "    }\n" +
    "}\n"
  );
}

function generateJsRules(rules: ErrorRules): string {
  const entries = rules.errors
    .map((error) => {
      const details = error.required_details.map((field) => `"${field}"`).join(", ");
      return `  ${error.code}: Object.freeze([${details}])`;
    })
    .join(",\n");

  return (
    generatedHeader(paths.source) +
    "export const REQUIRED_ERROR_DETAILS_BY_CODE = Object.freeze({\n" +
    `${entries}\n` +
    "});\n"
  );
}

function errorDetailsSchema(requiredDetails: string[]): JsonSchemaObject {
  return {
    type: "object",
    required: requiredDetails,
    properties: Object.fromEntries(requiredDetails.map((field) => [field, {}]))
  };
}

function sharedErrorDetailsDefs(rules: ErrorRules): Map<string, string> {
  const counts = new Map<string, number>();
  for (const error of rules.errors) {
    const key = error.required_details.join("\0");
    counts.set(key, (counts.get(key) ?? 0) + 1);
  }

  return new Map(
    [...counts.entries()]
      .filter(([, count]) => count > 1)
      .map(([key]) => {
        const fields = key.split("\0");
        return [key, generatedErrorDetailsName(fields)];
      })
  );
}

function generatedErrorDetailsName(fields: string[]): string {
  return `${generatedErrorDetailsDefPrefix}${fields.map(toPascalCase).join("")}`;
}

function isGeneratedErrorDetailsDefName(name: string): boolean {
  return generatedErrorDetailsDefPrefixes.some((prefix) => name.startsWith(prefix));
}

function toPascalCase(value: string): string {
  return value
    .split("_")
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join("");
}

function generateErrorDetailsAllOf(rules: ErrorRules): JsonSchemaObject[] {
  const sharedDefs = sharedErrorDetailsDefs(rules);
  return rules.errors.map((error) => {
    const detailsKey = error.required_details.join("\0");
    const sharedDefName = sharedDefs.get(detailsKey);
    return {
      if: {
        type: "object",
        properties: {
          code: {
            const: error.code
          }
        }
      },
      then: {
        type: "object",
        properties: {
          details: sharedDefName
            ? { $ref: `#/$defs/${sharedDefName}` }
            : errorDetailsSchema(error.required_details)
        }
      }
    };
  });
}

function applySharedErrorDetailsDefs(schema: JsonSchemaObject, rules: ErrorRules): void {
  const sharedDefs = sharedErrorDetailsDefs(rules);
  const defs = isJsonSchemaObject(schema.$defs) ? schema.$defs : {};
  schema.$defs = defs;
  for (const key of Object.keys(defs)) {
    if (isGeneratedErrorDetailsDefName(key)) {
      delete defs[key];
    }
  }
  for (const [fieldsKey, defName] of sharedDefs) {
    defs[defName] = errorDetailsSchema(fieldsKey.split("\0"));
  }
}

function generateProtocolResponseSchema(rules: ErrorRules): string {
  const schema = readJson(paths.protocolResponseSchema);
  assert(isJsonSchemaObject(schema), "protocol response schema root must be an object");
  const defs = schema.$defs;
  assert(isJsonSchemaObject(defs), "protocol response schema missing $defs");
  const failure = defs.failure;
  assert(isJsonSchemaObject(failure), "protocol response schema missing $defs.failure");
  const failureProperties = failure.properties;
  assert(isJsonSchemaObject(failureProperties), "protocol response schema missing $defs.failure.properties");
  const errorSchema = failureProperties.error;
  assert(isJsonSchemaObject(errorSchema), "protocol response schema missing $defs.failure.properties.error");
  const errorProperties = errorSchema.properties;
  assert(isJsonSchemaObject(errorProperties), "protocol response schema missing error.properties");
  const codeSchema = errorProperties.code;
  assert(isJsonSchemaObject(codeSchema), "protocol response schema missing error.properties.code");
  assert(errorSchema, "protocol response schema missing $defs.failure.properties.error");

  applySharedErrorDetailsDefs(schema, rules);
  codeSchema.enum = rules.errors.map((error) => error.code);
  errorSchema.allOf = generateErrorDetailsAllOf(rules);

  return `${JSON.stringify(schema, null, 2)}\n`;
}

function writeOrCheck(relPath: string, content: string, options: Options): void {
  const absPath = toAbs(relPath);
  const current = fs.existsSync(absPath) ? fs.readFileSync(absPath, "utf8") : null;
  if (current === content) {
    return;
  }

  if (options.checkOnly) {
    throw new Error(`${relPath} is out of date; run pnpm run generate:error-rules`);
  }

  fs.mkdirSync(path.dirname(absPath), { recursive: true });
  fs.writeFileSync(absPath, content, "utf8");
}

function main(args: string[]): void {
  const options = parseArgs(args);
  const rules = readJson(paths.source);
  validateRules(rules);

  writeOrCheck(paths.rustMod, generateRustMod(), options);
  writeOrCheck(paths.rustRules, generateRustRules(rules), options);
  writeOrCheck(paths.jsRules, generateJsRules(rules), options);
  writeOrCheck(paths.protocolResponseSchema, generateProtocolResponseSchema(rules), options);

  console.log(
    options.checkOnly
      ? "generated error rules ok"
      : `generated error rules from ${paths.source}`
  );
}

try {
  main(process.argv.slice(2));
} catch (error: unknown) {
  console.error(errorMessage(error));
  process.exitCode = 1;
}
