import fs from "node:fs";
import path from "node:path";

import { assert, readJson, toAbs } from "./tools/validators/fs-utils.ts";

const paths = {
  source: "docs/protocol/error-rules.json",
  rustMod: "crates/docnav-protocol/src/generated/mod.rs",
  rustRules: "crates/docnav-protocol/src/generated/error_rules.rs",
  jsRules: "scripts/tools/validators/generated/error-rules.ts",
  protocolResponseSchema: "docs/schemas/protocol-response.schema.json"
};

const generatedHeader = (sourcePath: any) =>
  `// This file is generated by scripts/generate-error-rules.ts from ${sourcePath}.\n` +
  "// Do not edit by hand.\n\n";

const generatedErrorDetailsDefPrefix = "generatedProtocolErrorDetails";
const generatedErrorDetailsDefPrefixes = [
  generatedErrorDetailsDefPrefix,
  "generatedErrorDetails"
];

function parseArgs(args: any) {
  const options = {
    checkOnly: false
  };

  for (const arg of args) {
    if (arg === "--check" && !options.checkOnly) {
      options.checkOnly = true;
      continue;
    }
    throw new Error(`unknown argument: ${arg}`);
  }

  return options;
}

function validateRules(rules: any) {
  assert(rules && typeof rules === "object", "error rules root must be an object");
  assert(typeof rules.version === "string", "error rules version must be a string");
  assert(Array.isArray(rules.errors), "error rules errors must be an array");
  assert(rules.errors.length > 0, "error rules errors must not be empty");

  const codes = new Set();
  const variants = new Set();
  for (const [index, error] of rules.errors.entries()) {
    const label = `errors[${index}]`;
    assert(error && typeof error === "object", `${label} must be an object`);
    assert(/^[A-Z][A-Z0-9_]*$/.test(error.code ?? ""), `${label}.code is invalid`);
    assert(
      /^[A-Z][A-Za-z0-9]*$/.test(error.rust_variant ?? ""),
      `${label}.rust_variant is invalid`
    );
    assert(
      Array.isArray(error.required_details) && error.required_details.length > 0,
      `${label}.required_details must be a non-empty array`
    );

    assert(!codes.has(error.code), `${label}.code duplicates ${error.code}`);
    assert(!variants.has(error.rust_variant), `${label}.rust_variant duplicates ${error.rust_variant}`);
    codes.add(error.code);
    variants.add(error.rust_variant);

    const detailFields = new Set();
    for (const field of error.required_details) {
      assert(/^[a-z][a-z0-9_]*$/.test(field), `${label}.required_details contains invalid field ${field}`);
      assert(!detailFields.has(field), `${label}.required_details duplicates ${field}`);
      detailFields.add(field);
    }
  }
}

function generateRustMod() {
  return `${generatedHeader(paths.source)}pub(crate) mod error_rules;\n`;
}

function generateRustRules(rules: any) {
  const arms = rules.errors
    .map((error: any) => {
      const details = error.required_details.map((field: any) => `"${field}"`).join(", ");
      return `        StableErrorCode::${error.rust_variant} => &[${details}],`;
    })
    .join("\n");

  return (
    generatedHeader(paths.source) +
    "use crate::StableErrorCode;\n\n" +
    "pub(crate) const fn required_details(code: StableErrorCode) -> &'static [&'static str] {\n" +
    "    match code {\n" +
    `${arms}\n` +
    "    }\n" +
    "}\n"
  );
}

function generateJsRules(rules: any) {
  const entries = rules.errors
    .map((error: any) => {
      const details = error.required_details.map((field: any) => `"${field}"`).join(", ");
      return `  ${error.code}: Object.freeze([${details}])`;
    })
    .join(",\n");

  return (
    generatedHeader(paths.source) +
    "export const REQUIRED_ERROR_DETAILS_BY_CODE = Object.freeze({\n" +
    `${entries}\n` +
    "});\n"
  );
}

function errorDetailsSchema(requiredDetails: any) {
  return {
    type: "object",
    required: requiredDetails,
    properties: Object.fromEntries(requiredDetails.map((field: any) => [field, {}]))
  };
}

function sharedErrorDetailsDefs(rules: any) {
  const counts = new Map();
  for (const error of rules.errors) {
    const key = error.required_details.join("\0");
    counts.set(key, (counts.get(key) ?? 0) + 1);
  }

  return new Map(
    [...counts.entries()]
      .filter(([, count]) => count > 1)
      .map(([key]) => {
        const fields = key.split("\0");
        return [key, generatedErrorDetailsName(fields)];
      })
  );
}

function generatedErrorDetailsName(fields: any) {
  return `${generatedErrorDetailsDefPrefix}${fields.map(toPascalCase).join("")}`;
}

function isGeneratedErrorDetailsDefName(name: any) {
  return generatedErrorDetailsDefPrefixes.some((prefix) => name.startsWith(prefix));
}

function toPascalCase(value: any) {
  return value
    .split("_")
    .map((part: any) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join("");
}

function generateErrorDetailsAllOf(rules: any) {
  const sharedDefs = sharedErrorDetailsDefs(rules);
  return rules.errors.map((error: any) => {
    const detailsKey = error.required_details.join("\0");
    const sharedDefName = sharedDefs.get(detailsKey);
    return {
      if: {
        type: "object",
        properties: {
          code: {
            const: error.code
          }
        }
      },
      then: {
        type: "object",
        properties: {
          details: sharedDefName
            ? { $ref: `#/$defs/${sharedDefName}` }
            : errorDetailsSchema(error.required_details)
        }
      }
    };
  });
}

function applySharedErrorDetailsDefs(schema: any, rules: any) {
  const sharedDefs = sharedErrorDetailsDefs(rules);
  schema.$defs = schema.$defs ?? {};
  for (const key of Object.keys(schema.$defs)) {
    if (isGeneratedErrorDetailsDefName(key)) {
      delete schema.$defs[key];
    }
  }
  for (const [fieldsKey, defName] of sharedDefs) {
    schema.$defs[defName] = errorDetailsSchema(fieldsKey.split("\0"));
  }
}

function generateProtocolResponseSchema(rules: any) {
  const schema = readJson(paths.protocolResponseSchema);
  const errorSchema = schema?.$defs?.failure?.properties?.error;
  assert(errorSchema, "protocol response schema missing $defs.failure.properties.error");
  assert(errorSchema.properties?.code, "protocol response schema missing error.properties.code");

  applySharedErrorDetailsDefs(schema, rules);
  errorSchema.properties.code.enum = rules.errors.map((error: any) => error.code);
  errorSchema.allOf = generateErrorDetailsAllOf(rules);

  return `${JSON.stringify(schema, null, 2)}\n`;
}

function writeOrCheck(relPath: any, content: any, options: any) {
  const absPath = toAbs(relPath);
  const current = fs.existsSync(absPath) ? fs.readFileSync(absPath, "utf8") : null;
  if (current === content) {
    return;
  }

  if (options.checkOnly) {
    throw new Error(`${relPath} is out of date; run pnpm run generate:error-rules`);
  }

  fs.mkdirSync(path.dirname(absPath), { recursive: true });
  fs.writeFileSync(absPath, content, "utf8");
}

function main(args: any) {
  const options = parseArgs(args);
  const rules = readJson(paths.source);
  validateRules(rules);

  writeOrCheck(paths.rustMod, generateRustMod(), options);
  writeOrCheck(paths.rustRules, generateRustRules(rules), options);
  writeOrCheck(paths.jsRules, generateJsRules(rules), options);
  writeOrCheck(paths.protocolResponseSchema, generateProtocolResponseSchema(rules), options);

  console.log(
    options.checkOnly
      ? "generated error rules ok"
      : `generated error rules from ${paths.source}`
  );
}

try {
  main(process.argv.slice(2));
} catch (error: any) {
  console.error(error.message);
  process.exitCode = 1;
}
